export const QUERYFORGE_PUBLISHER = 'queryforge';
export const QUERYFORGE_EXTENSION_NAME = 'queryforge-editor';
export const QUERYFORGE_EXTENSION_ID = `${QUERYFORGE_PUBLISHER}.${QUERYFORGE_EXTENSION_NAME}`;
